---
title: "Untitled"
author: "Novdano"
date: "9/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
T = c(0.25, 0.5, 0.75, 1)
strikes = list(c(95, 100 ,105),
            c(95, 100 ,105),
            c(100 ,105, 110),
            c(100 ,105, 110))
prices = list(c(6.5757, 2.8223, 0.6335),
            c(8.1165, 4.3850, 1.7263),
            c(6.0865, 3.1820, 1.2347),
            c(7.7710, 4.7369, 2.4165))
```



```{r}
HestonCallClosedForm <-
    function(lambda, vbar, eta, rho, v0, r, tau, S0, K) {
	PIntegrand <- function(u, lambda, vbar, eta, rho, v0, r, tau, S0, K, j) {
            F <- S0*exp(r*tau)
            x <- log(F/K)
            a <- lambda * vbar
            
            if (j == 1) {
                b <- lambda - rho* eta
                alpha <- - u^2/2 - u/2 * 1i + 1i * u
                beta <- lambda - rho * eta - rho * eta * 1i * u
            } else {
                b <- lambda
                alpha <- - u^2/2 - u/2 * 1i
                beta <- lambda - rho * eta * 1i * u
            }
            
            gamma <- eta^2/2
            d <- sqrt(beta^2 - 4*alpha*gamma)
            rplus <- (beta + d)/(2*gamma)
            rminus <- (beta - d)/(2*gamma)
            g <- rminus / rplus
            
            D <- rminus * (1 - exp(-d*tau))/(1-g*exp(-d*tau))
            C <- lambda * (rminus * tau - 2/(eta^2) * log( (1-g*exp(-d*tau))/(1-g) ) )
            
            top <- exp(C*vbar + D*v0 + 1i*u*x)
            bottom <- (1i * u)
            Re(top/bottom)
	}
	
	P <- function(lambda, vbar, eta, rho, v0, r, tau, S0, K, j) {
            value <- integrate(PIntegrand, lower = 0, upper = Inf,
                               lambda, vbar, eta, rho, v0, r, tau,
                               S0, K, j, subdivisions=1000)$value
            0.5 + 1/pi * value
	}

    A <- S0*P(lambda, vbar, eta, rho, v0, r, tau, S0, K, 1)
    B <- K*exp(-r*tau)*P(lambda, vbar, eta, rho, v0, r, tau, S0, K, 0)
    A-B
  }
```

```{r}
HestonCallMonteCarlo <-
    function(lambda, vbar, eta, rho, v0, r, tau, S0, K, nSteps=2000, nPaths=3000, vneg=2) {

        n <- nSteps
        N <- nPaths
        
        dt <- tau / n
        
        negCount <- 0
        
        S <- rep(S0,N)
        v <- rep(v0,N)
        
        for (i in 1:n)
            {
                W1 <- rnorm(N);
                W2 <- rnorm(N);
                W2 <- rho*W1 + sqrt(1 - rho^2)*W2;

                sqvdt <- sqrt(v*dt)
                S <- S*exp((r-v/2)*dt + sqrt(v * dt) * W1)
                
                if ((vneg == 3) & (2*lambda*vbar/(eta^2) <= 1)) {
                    cat("Variance not guaranteed to be positive with choice of lambda, vbar, and eta\n")
                    cat("Defaulting to Reflection + Milstein method\n")
                    vneg = 2
                }

                if (vneg == 0){
                    ## Absorbing condition
                    v <- v + lambda*(vbar - v)* dt + eta * sqvdt * W2
                    negCount <- negCount + length(v[v < 0])
                    v[v < 0] <- 0
                }
                if (vneg == 1){
                    ## Reflecting condition
                    sqvdt <- sqrt(v*dt)
                    v <- v + lambda*(vbar - v)* dt + eta * sqvdt * W2
                    negCount <- negCount + length(v[v < 0])
                    v <- ifelse(v<0, -v, v)
                }
                if (vneg == 2) {
                    ## Reflecting condition + Milstein
                    v <- (sqrt(v) + eta/2*sqrt(dt)*W2)^2 - lambda*(v-vbar)*dt - eta^2/4*dt
                    negCount <- negCount + length(v[v < 0])
                    v <- ifelse(v<0, -v, v)     
                }
                if (vneg == 3) {
                    ## Alfonsi - See Gatheral p.23
                    v <- v -lambda*(v-vbar)*dt +eta*sqrt(v*dt)*W2 - eta^2/2*dt      
                }
            }
        
        negCount <- negCount / (n*N);

        ## Evaluate mean call value for each path
        V <- exp(-r*tau)*(S>K)*(S - K); # Boundary condition for European call
        AV <- mean(V);
        AVdev <- 2 * sd(V) / sqrt(N);

        list(value=AV, lower = AV-AVdev, upper = AV+AVdev, zerohits = negCount)
    }
```



```{r}
kappa = 10.97858327
theta = 0.027225000000000003
phi = 0.01362476
rho = -0.55156066
HestonCallClosedForm(kappa, theta, phi, rho, 0.11, 0.0411, 1.5, 100, 120)
HestonCallClosedForm(kappa, theta, phi, rho, 0.17, 0.0411, 0.5, 110, 120)
#HestonCallMonteCarlo(kappa, theta, phi, rho, 0.11, 0.0411, 1.5, 100, 80, vneg = 0)
```


```{r}
MSE <- function(vec1, vec2){
  ms <- (vec1-vec2)^2
  return ((sum(ms))^0.5)/length(vec1)
}

loss_function <- function(param_vectors){
  a <- param_vectors[[1]]
  theta <- param_vectors[[2]]
  miu <- param_vectors[[3]]
  rho<- param_vectors[[4]]
  kappa <- (a + miu^2)/(2*theta)
  sv_est = c()
  mkt_px = c()
  for(i in 1:length(T)){
    for(j in 1:length(strikes[[i]])){
      r = 0.0411
      tau = T[[i]]
      S = 100
      K = strikes[[i]][[j]]
      mkt_px = c( mkt_px, prices[[i]][[j]] )
      sv_est = c( sv_est, HestonCallClosedForm(kappa, theta, miu, rho, 0.11, r, tau, S, K) )
    }
  }
  #print(mkt_px)
  #print(sv_est)
  return (MSE(sv_est, mkt_px))
}
```

```{r}
kappa = 10.97858327
theta = 0.02514962
phi = 0.262476
rho = -0.55156066
alpha = 2*kappa * theta - phi^2
loss_function(c(alpha, theta, phi, rho))
```


```{r}
neighbor <- function(param_vectors){
  a <- param_vectors[[1]]
  theta <- param_vectors[[2]]
  nu <- param_vectors[[3]]
  rho<- param_vectors[[4]]
  sdA <- 1
  sdT <- 0.02
  sdN <- 0.02
  sdR <- 0.01
  newA <- rnorm(1, a, sdA)
  newT <- rnorm(1, theta, sdT)
  newN <- rnorm (1, nu, sdN)
  newR <- rnorm(1, rho, sdR)
  while (newA<0 || newT <0.05 ||newT>1 || ((newA + nu^2)/2*newT) <0 || ((newA + nu^2)/2*newT) >5 || nu > 1 || nu < 0
         ||rho< -1||rho > 1 ){
    sdA <- sdA * 2
    sdT <- sdT * 2
    sdN <- sdN * 2
    sdR <- sdR * 2
    newA <- rnorm(1, a, sdA)
    newT <- rnorm(1, theta, sdT)
    newN <- rnorm (1, nu, sdN)
    newR <- rnorm(1, rho, sdR)
  }
  return (c(newA, newT, newN, newR))
}

acceptance_probability <- function(old_cost, new_cost, T){
  return (exp((old_cost-new_cost)/T))
}

simulated_annealing <- function(param_vectors){
  a <- param_vectors[[1]]
  theta <- param_vectors[[2]]
  nu <- param_vectors[[3]]
  rho<- param_vectors[[4]]
  sol <- param_vectors
  old_cost <- loss_function(c(a, theta, nu, rho))
  best_cost <- 100000
  best_sol <- NULL
  T <- 1.0
  T_min <- 1e-4
  alpha <- 0.9
  while (T > T_min){
    print(T)
    a <- best_sol[[1]]
    theta <- best_sol[[2]]
    miu <- best_sol[[3]]
    rho <- best_sol[[4]]
    kappa <- (a + miu^2)/ (2*theta)
    print(c(kappa, theta, miu, rho))
    for (i in 1: 100){
      new_sol <- neighbor(sol)
      #print(new_sol)
      new_cost <- loss_function(new_sol)
      if(new_cost < old_cost){
        sol <- new_sol
        if( new_cost < best_cost){
          best_sol = new_sol
        }
      } else {
        ap = acceptance_probability(old_cost, new_cost, T)
        if (ap > runif(1, 0, 1)){
          sol <- new_sol
          old_cost <- new_cost 
        } 
      }
    }
    T <- T * alpha
  }
  return (c(sol, old_cost))
}
```

```{r}
kappa = 10.97858327
theta = 0.02514962
phi = 0.262476
rho = -0.55156066
alpha = 2*kappa * theta - phi^2
params <- simulated_annealing(c(alpha, theta, phi, rho))
a <- params[[1]]
theta <- params[[2]]
miu <- params[[3]]
rho <- params[[4]]
kappa <- (a + miu^2)/ (2*theta)
c(kappa, theta, miu, rho)
c(params[[5]])
```





```{r}
sv_est = rep(0, length(T) * length(strikes[[1]]))
mkt_px = rep(0, length(T) * length(strikes[[1]]))
for(i in 1:length(T)){
  for(j in 1:length(strikes[[i]])){
    r = 0.0411
    tau = T[[i]]
    S = 100
    K = strikes[[i]][[j]]
    mkt_px[[i]] = prices[[i]][[j]]
    sv_est[[i]] = HestonCallClosedForm(kappa, theta, miu, rho, 0.11, r, tau, S, K)
  }
}
```

```{r}
prices[[1]][[3]]
```


```{r}

for(i in length(T) * length(strikes[[1]])){
  
}
```





